name: poi-trunk-deploy

# deploy to ACR

on:
  push:
    branches: 
      - trunk
    # paths:
    #   - apis/poi/**

jobs:
  build:

    runs-on: ubuntu-latest

    env:
      working-directory: ./apis/poi
      WEBDIR: web
      REGISTRYNAME: openhackvn13pzx8acr 
      APPID: ${{ secrets.APP_ID }}
      SERVICEPRINPWD: ${{ secrets.SERVICE_PRIN_PWD }}
      TENANTID: ${{ secrets.TENANT_ID }}

    steps: 

    - uses: actions/checkout@v2
    
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 2.1  
    
    - name: Install dependencies
      run: dotnet restore
      working-directory: ${{env.working-directory}}
      
    - name: Build
      run: dotnet build --configuration Release --no-restore
      working-directory: ${{env.working-directory}}

    - name: Build / Deploy POI image
      working-directory: ${{env.working-directory}}
      run: |
        echo "Building API-POI image..."
        cd $WEBDIR
        az login --service-principal --username $APPID --password $SERVICEPRINPWD --tenant $TENANTID
        az acr build --image devopsoh/api-poi:$GITHUB_RUN_NUMBER --registry $REGISTRYNAME --file Dockerfile .
        echo "The docker file with tag " $GITHUB_RUN_NUMBER " has been uploaded to ACR."

      shell: bash 
